### ISSUE TITLE
Quest resource has no `update` method

### ISSUE THREAD

**Issue by jonbonazza** [ShomyKohai/quest-system#1]
`ActiveQuestPool.update_objective` calls the `update` method on `Quest`, however `Quest` has no `update` method. I suspect that `Quest` should have a default `update` method that simple sets `objective_completed = true`?

If this sounds correct, I can open a PR.

**Comment by ShomyKohai** [comment]
Oops, you're right, the method is indeed missing.

I'll merge your PR! Thanks!
