### ISSUE TITLE
Support translation

### ISSUE THREAD

**Issue by Supamiu** [shomykohai/quest-system#10]
# Describe the feature

First of all, amazing addon !

As I was benchmarking it in order to see if it would be a good fit for my game project, I ran into a major things I need that I didn't find inside the code: translation. I'm talking translation of the quest's name, description and goal (ideally with parameters that anyone can add by extending the `Quest`ressource).

## Why do you think it should be added?

Quest-system is a great addon that does the job while keeping things simple, by adding translation support, it'd make it the perfect quest addon for many games, especially with the fact that your example shows a combo with Dialogue Manager, another amazing addon, which happens to have great translation support.

**Comment by Supamiu** [comment]
Actually, this might be more of a documentation feature, since while I was trying to implement i18n quests in my project, I realized this was mainly on the UI side, meaning that the quest can just hold its translation keys everywhere and have the UI call the `tr` method to display them.

**Comment by shomykohai** [comment]
Thanks for your feedback!

I agree with you, translation support would really enhance the developer experience.
As you said, the easiest way is surely to hold translation keys in the Quest Resource itself, though I'll surely add support for the UI part.

Again, thanks for your feedback!

**Comment by shomykohai** [comment]
> # Describe the feature
> 
> First of all, amazing addon !
> 
> As I was benchmarking it in order to see if it would be a good fit for my game project, I ran into a major things I need that I didn't find inside the code: translation. I'm talking translation of the quest's name, description and goal (ideally with parameters that anyone can add by extending the `Quest`ressource).
> ## Why do you think it should be added?
> 
> Quest-system is a great addon that does the job while keeping things simple, by adding translation support, it'd make it the perfect quest addon for many games, especially with the fact that your example shows a combo with Dialogue Manager, another amazing addon, which happens to have great translation support.

Addes support for generating POT files and updated the documentation as well in https://github.com/shomykohai/quest-system/tree/support-translations (I'll merge it tomorrow into main).
If you want you can try it already downloading the addon from that branch.
