### ISSUE TITLE
Add unit testing for testing the plugin

### ISSUE THREAD

**Issue by GustavoLR548** [shomykohai/quest-system#23]
# Describe the feature

I believe adding unit testing would be a great quality of life feature for the plugin. 

## Why do you think it should be added?

It would make it easier to verify if new changes breaks already existing features. It doesn't need to use a unit testing plugin, you could just make a scene in the repository (not the addon), that verifies if the functionalities of the plugin all work as intended, using the ```assert``` function.

**Comment by shomykohai** [comment]
I was thinking about adding Unit Tests for a while now, I just have to find the time to actually do it.

My idea was to do something like bitbrain's Pandora where unit tests are run with github actions on every commit/PR.
For that using a unit testing plugin like gdunit4 would be ideal.

**Comment by shomykohai** [comment]
I was thinking about adding Unit Tests for a while now, I just have to find the time to actually do it.

My idea was to do something like bitbrain's Pandora where unit tests are run with github actions on every commit/PR.
For that using a unit testing plugin like gdunit4 would be ideal.

**Comment by shomykohai** [comment]
> # Describe the feature
> 
> I believe adding unit testing would be a great quality of life feature for the plugin.
> ## Why do you think it should be added?
> 
> It would make it easier to verify if new changes breaks already existing features. It doesn't need to use a unit testing plugin, you could just make a scene in the repository (not the addon), that verifies if the functionalities of the plugin all work as intended, using the `assert` function.

Added in #24.
