### ISSUE TITLE
Project exported for HTML or Android, quests not loaded and error on console:  No loader found for resource "file_name.res"

### ISSUE THREAD

**Issue by ManuelMacchia** [shomykohai/quest-system#25]
# Describe the bug
 
The plugin works like a charm when I'm testing my game locally, but when I try to run it using the Remote Debug, or export it fro Android o HTML I receive an error like this, and the quests are not loaded:

`tmp_js_export.js:54796 USER ERROR: No loader found for resource: res://.godot/exported/133200997/export-36fca5acabeb0ef7692f435da8de8218-quest-01.res (expected type: Quest)`

I don't know why it tries to load this .res file. Of course on my project exist the file quest-01.tres (and not .res) and it is properly exported.

May I miss something on the export configuration?

Thanks in advance for you suggestion

- What was the expected behaviour?
The plugin should be able to load all the file .tres added for my quests

- What happened instead?
This error occurred 
`tmp_js_export.js:54796 USER ERROR: No loader found for resource: res://.godot/exported/133200997/export-36fca5acabeb0ef7692f435da8de8218-quest-01.res (expected type: Quest)`

## Information
* Version of Godot affected: 
* 4.2.2
* quest-system Plugin version: 1.5.0 (but I've replicated the same issue with the 1.4 and 1.3)

## Steps to reproduce the bug & eventual errors

 * quest-system plugin properly installed and configured
 * added my quest and all the code to handle them, during the local test everything works properly
 * configure the export for HTML project (also the Android version)
 *  export to HTML or Run "Remote Debug"

**Comment by shomykohai** [comment]
Hey there!

Could you share the snippet of code where you load the quests?

I assume you're loading them doing something like
```
ResourceLoader.load("path/to/quest")
```

Also, would you mind sharing a minimal project reproducing the issue?

**Comment by ManuelMacchia** [comment]
Thanks for your reply. Here the snippet of code where I'm loading the quest

```
const QUEST_PATH: String = "res://quests/%s.tres"

func get_quest_from_name(quest_name: String) -> Quest:
	var quest: Quest = ResourceLoader.load(QUEST_PATH % quest_name, "Quest")
	return quest
```

This function is called from several other functions on a shortcuts.gd file I'm using for easily perform actions against the quest, here an example

```
func start_quest(quest_name: String) -> void:
	var quest: Quest = get_quest_from_name(quest_name)
	if quest == null: return
	QuestSystem.start_quest(quest)
	global_events.emit_new_active_quest_signal(quest_name)
	item_state.active_quest_name = quest_name
```

I'll try to prepare also a kind of minimal project in order to reproduce the issue, in the meantime, thanks for the support

Manuel

**Comment by shomykohai** [comment]
I can already see the issue, unfortunately I forgot to apply the fix on the example project.

The issue happens when you load the Quest:
```gdscript
... 
   var quest: Quest = ResourceLoader.load(QUEST_PATH % quest_name, "Quest")
...
```

The fix is to remove the second argument from the load function:
```gdscript
... 
   var quest: Quest = ResourceLoader.load(QUEST_PATH % quest_name)
...
```

Let me know if this fixes the issue. It did for me on another project, with the difference that it was exported for windows.

**Comment by ManuelMacchia** [comment]
Great, 
this definitely fix the issue.
This really save my day.

Thanks

**Comment by shomykohai** [comment]
Good to hear that!
I'll update the example project to remove the bug.
