### ISSUE TITLE
Adding a singal for when a quest objective has been completed.

### ISSUE THREAD

**Issue by dicemaster5** [shomykohai/quest-system#26]
# Describe the feature
When a quest's `objective_completed` bool has been set to true a `quest_objective_completed` singal is emitted.

## Why do you think it should be added?
This signal will be helpful in situations in which you want to be informed that a quest objective is complete before the actual quest itself has been marked as completed.

An example use case for me right now would be to display unqiue npc dialogue about the quest being comepleted before the actual quest get's completed at the end of the npc dialogue interaction.

**Comment by shomykohai** [comment]
Sounds like a great idea! 

Please note that, as for the current architecture of the addon, this signal will be probably be emitted from the Quest class and not the QuestSystem autoload.

**Comment by dicemaster5** [comment]
Yes, this is where I expected it to be setup and emitted from.
I've got it setup like this in my current project.
![image](https://github.com/user-attachments/assets/45e2615f-2929-4be8-9bf5-756a5ef4eeeb)

I'd be happy to put up a PR with this implmentation if you think it's good enough. 😄 
But unsure on what the best name for the signal should be.

**Comment by shomykohai** [comment]
> Yes, this is where I expected it to be setup and emitted from.
> I've got it setup like this in my current project.
> ![image](https://github.com/user-attachments/assets/45e2615f-2929-4be8-9bf5-756a5ef4eeeb)
> 
> I'd be happy to put up a PR with this implmentation if you think it's good enough. 😄 
> But unsure on what the best name for the signal should be.

In my opinion it would be better to emit the signal in any case, and pass the value of the `objective_completed` variable:

```gdscript

signal objective_status_updated(value: bool)

... 
    set(value):
        objective_completed = value
        objective_status_updated.emit(value)

```

This in my opinion would allow for better control in any scenario compared to just emitting when completed (i.e. if someone has a feature that sets `objective_completed` back to false if the condition is not met anymore) 

Feel free to open a PR anyway!
Remember to update the documentation too under the `docs` directory.

**Comment by dicemaster5** [comment]
> In my opinion it would be better to emit the signal in any case, and pass the value of the objective_completed variable:
This in my opinion would allow for better control in any scenario compared to just emitting when completed (i.e. if someone has a feature that sets objective_completed back to false if the condition is not met anymore)

Agreed, and good reasoning!

> Feel free to open a PR anyway! Remember to update the documentation too under the `docs` directory.
 
I've opened up a PR #27 for this change and made the relevant documentation changes. Thanks!
