### ISSUE TITLE
Quest System docs unreadable

### ISSUE THREAD

**Issue by this-is-envy** [shomykohai/quest-system#29]
This system comes pretty well recommended but it's enough of a pain to read the docs that I skip it whenever I'm quest related stuff ends up as a TODO on a game I'm building. Which is a shame because it seems like a reasonable solution.

And to be clear by "pain to read" I mean literally unreadable:

![image](https://github.com/user-attachments/assets/d7c7c9eb-5c07-4f9c-a23e-56f111caba35)

I've repro'd this in chrome, firefox, and edge. It seems to work in opera but I don't generally keep that installed. Issue seems to come from `base-background-color` and `sidebar-background` in `theme.css` as changing them to `#fff` for this block in devtools makes things usable.

```
:root {
  --base-background-color: #1b1e24;
  --link-color: #ff9100;
  --link-text-decoration: ;
  --sidebar-background: #1b1e24;
  --search-background: #1b1e24;
}
```

Presumably you could also override text color if you're deeply committed to dark mode but idk if there are other failure modes with that.

**Comment by shomykohai** [comment]
I was able to reproduce the issue in Firefox, works fine with brave.

Could you check if enabling dark mode system wide you still get the issue? If not, it's a problem with the dark mode detection. There's, should be a light theme too in the documentation that does not seem to apply well.

**Comment by shomykohai** [comment]
@this-is-envy I've updated the theme.css file, now it should automatically apply the light theme as intended.

Could you check if it's readable now? Remember to clear the cache and cookies of the website to be sure.

On my end it works just fine now.

**Comment by this-is-envy** [comment]
Oh, I missed this

> Could you check if enabling dark mode system wide you still get the issue? If not, it's a problem with the dark mode detection. There's, should be a light theme too in the documentation that does not seem to apply well.

For what it's worth after your most recent update it works as expected in both light and dark mode (with the caveat that the title image has dark mode background so plausible there is still a light/dark detection issue).

**Comment by shomykohai** [comment]
Glad it works as intended now!

Anyway, my fault too for not having tested the light mode as well as I did with dark mode during the time I added documentation 😅.

**Comment by shomykohai** [comment]
> Oh, I missed this
> 
> > Could you check if enabling dark mode system wide you still get the issue? If not, it's a problem with the dark mode detection. There's, should be a light theme too in the documentation that does not seem to apply well.
> 
> For what it's worth after your most recent update it works as expected in both light and dark mode (with the caveat that the title image has dark mode background so plausible there is still a light/dark detection issue).

As for the image, it's just that I didn't make one with white background. I'll look into it these days! The important thing now is that the documentation itself is usable!
